### ISSUE TITLE
Project Submission

### ISSUE THREAD

**Issue by gaks1** [gaks1/recipe-app#11]
Hi, we are a two-member team this is our [project](https://github.com/users/gaks1/projects/2/views/1).
- Members: @raihan2bd , @gaks1

**Comment by descholar-ceo** [comment]
Hi @gaks1 && @raihan2bd 🤝 , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
👍🏽 The project's requirements are distributed fairly ✔️ 
👍🏽 All cards are assigned ✔️ 
👍🏽 All cards have descriptive title and description ✔️ 

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by raihan2bd** [comment]
Hi @descholar-ceo ✋, Thanks a lot for reviewing our project. 👍
